-- MySQL Script generated by MySQL Workbench
-- Tue Dec 13 09:37:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment` (
  `payment_id` INT NOT NULL,
  `paypal_username` VARCHAR(45) NULL,
  `card_num` INT NULL,
  `expire_month` ENUM('01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12') NULL,
  `expire_year` INT NULL,
  `secure_code` INT NULL,
  `total` DECIMAL(2) NULL,
  `payment_date` DATETIME NULL,
  PRIMARY KEY (`payment_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subscription` (
  `subscription_id` INT NOT NULL AUTO_INCREMENT,
  `started_at` DATETIME NULL,
  `renewal_date` DATETIME NULL,
  `payment_id` INT NOT NULL,
  PRIMARY KEY (`subscription_id`, `payment_id`),
  INDEX `fk_subscription_payment_method_idx` (`payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_subscription_payment_method`
    FOREIGN KEY (`payment_id`)
    REFERENCES `mydb`.`payment` (`payment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`songs` (
  `songs_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(30) NULL,
  `length_seconds` INT NULL,
  `times_played` INT NULL,
  PRIMARY KEY (`songs_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`playlists` (
  `playlists_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `songs_sum` INT NULL,
  `created_at` DATETIME NULL,
  `status` ENUM('active', 'inactive') NULL,
  `status_change_date` DATETIME NULL,
  `songs_id` INT NOT NULL,
  PRIMARY KEY (`playlists_id`, `songs_id`),
  INDEX `fk_playlists_songs1_idx` (`songs_id` ASC) VISIBLE,
  CONSTRAINT `fk_playlists_songs1`
    FOREIGN KEY (`songs_id`)
    REFERENCES `mydb`.`songs` (`songs_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`albums` (
  `albums_id` INT NOT NULL AUTO_INCREMENT,
  `songs_id` INT NOT NULL,
  `title` VARCHAR(30) NULL,
  `release_year` INT NULL,
  `cover` BLOB NULL,
  PRIMARY KEY (`albums_id`, `songs_id`),
  INDEX `fk_albums_songs1_idx` (`songs_id` ASC) VISIBLE,
  CONSTRAINT `fk_albums_songs1`
    FOREIGN KEY (`songs_id`)
    REFERENCES `mydb`.`songs` (`songs_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`artists` (
  `artists_id` INT NOT NULL AUTO_INCREMENT,
  `albums_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `picture` BLOB NULL,
  `related_artists_id` INT NOT NULL,
  PRIMARY KEY (`artists_id`, `albums_id`, `related_artists_id`),
  INDEX `fk_artists_albums1_idx` (`albums_id` ASC) VISIBLE,
  INDEX `fk_artists_artists1_idx` (`related_artists_id` ASC) VISIBLE,
  CONSTRAINT `fk_artists_albums1`
    FOREIGN KEY (`albums_id`)
    REFERENCES `mydb`.`albums` (`albums_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_artists_artists1`
    FOREIGN KEY (`related_artists_id`)
    REFERENCES `mydb`.`artists` (`artists_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `users_id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM('free', 'premium') NULL,
  `mail` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `birthdate` DATETIME NULL,
  `sex` ENUM('male', 'female', 'not specified') NULL,
  `country` VARCHAR(45) NULL,
  `zipcode` VARCHAR(45) NULL,
  `subscription_id` INT NOT NULL,
  `playlists_id` INT NOT NULL,
  `artists_id` INT NOT NULL,
  `albums_id` INT NOT NULL,
  `songs_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `subscription_id`, `playlists_id`, `artists_id`, `albums_id`, `songs_id`),
  INDEX `fk_users_subscription1_idx` (`subscription_id` ASC) VISIBLE,
  INDEX `fk_users_playlists1_idx` (`playlists_id` ASC) VISIBLE,
  INDEX `fk_users_artists1_idx` (`artists_id` ASC, `albums_id` ASC) VISIBLE,
  INDEX `fk_users_songs1_idx` (`songs_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_subscription1`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `mydb`.`subscription` (`subscription_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_playlists1`
    FOREIGN KEY (`playlists_id`)
    REFERENCES `mydb`.`playlists` (`playlists_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_artists1`
    FOREIGN KEY (`artists_id` , `albums_id`)
    REFERENCES `mydb`.`artists` (`artists_id` , `albums_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_songs1`
    FOREIGN KEY (`songs_id`)
    REFERENCES `mydb`.`songs` (`songs_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_adds_songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_adds_songs` (
  `users_id` INT NOT NULL,
  `playlists_id` INT NOT NULL,
  `songs_id` INT NOT NULL,
  `timestamp` DATETIME NULL,
  PRIMARY KEY (`users_id`, `playlists_id`, `songs_id`),
  INDEX `fk_users_has_songs_songs1_idx` (`songs_id` ASC) VISIBLE,
  INDEX `fk_users_has_songs_users1_idx` (`users_id` ASC, `playlists_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_songs_users1`
    FOREIGN KEY (`users_id` , `playlists_id`)
    REFERENCES `mydb`.`users` (`users_id` , `playlists_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_has_songs_songs1`
    FOREIGN KEY (`songs_id`)
    REFERENCES `mydb`.`songs` (`songs_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
