-- MySQL Script generated by MySQL Workbench
-- Mon Jan 16 15:52:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8mb3 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`categoria_pizzes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`categoria_pizzes` (
  `categoria_pizzes_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`categoria_pizzes_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`productes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`productes` (
  `productes_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NULL DEFAULT NULL,
  `descripcio` VARCHAR(45) NULL DEFAULT NULL,
  `imatge` BLOB NULL DEFAULT NULL,
  `preu` DECIMAL(2,0) NULL DEFAULT NULL,
  `tipus` ENUM("pizza", "hamburguesa", "beguda") NULL,
  `categoria_pizzes_id` INT NULL,
  PRIMARY KEY (`productes_id`, `categoria_pizzes_id`),
  INDEX `fk_productes_categoria_pizzes1_idx` (`categoria_pizzes_id` ASC) VISIBLE,
  CONSTRAINT `fk_productes_categoria_pizzes1`
    FOREIGN KEY (`categoria_pizzes_id`)
    REFERENCES `pizzeria`.`categoria_pizzes` (`categoria_pizzes_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`direccions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`direccions` (
  `direccions_id` INT NOT NULL AUTO_INCREMENT,
  `carrer` VARCHAR(45) NULL DEFAULT NULL,
  `num` INT NULL DEFAULT NULL,
  `pis` INT NULL DEFAULT NULL,
  `porta` VARCHAR(45) NULL DEFAULT NULL,
  `codi_postal` INT NULL DEFAULT NULL,
  `localitat` VARCHAR(45) NULL DEFAULT NULL,
  `provincia` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`direccions_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`clients` (
  `clients_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `cognom1` VARCHAR(45) NULL DEFAULT NULL,
  `cognom2` VARCHAR(45) NULL DEFAULT NULL,
  `telefon` VARCHAR(45) NULL DEFAULT NULL,
  `direccions_id` INT NOT NULL,
  PRIMARY KEY (`clients_id`, `direccions_id`),
  INDEX `fk_clients_direccions_idx` (`direccions_id` ASC) VISIBLE,
  CONSTRAINT `fk_clients_direccions`
    FOREIGN KEY (`direccions_id`)
    REFERENCES `pizzeria`.`direccions` (`direccions_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`pizzeria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`pizzeria` (
  `pizzeria_id` INT NOT NULL AUTO_INCREMENT,
  `direccions_id` INT NOT NULL,
  PRIMARY KEY (`pizzeria_id`, `direccions_id`),
  INDEX `fk_pizzeria_direccions1_idx` (`direccions_id` ASC) VISIBLE,
  CONSTRAINT `fk_pizzeria_direccions1`
    FOREIGN KEY (`direccions_id`)
    REFERENCES `pizzeria`.`direccions` (`direccions_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comanda` (
  `comanda_id` INT NOT NULL AUTO_INCREMENT,
  `data_hora` DATETIME NULL DEFAULT NULL,
  `tipus` ENUM('domicili', 'botiga') NULL DEFAULT NULL COMMENT '2 valors possibles: botiga o domicili',
  `pizzes` INT NULL DEFAULT NULL,
  `hamburgueses` INT NULL DEFAULT NULL,
  `begudes` INT NULL DEFAULT NULL,
  `preu_total` DECIMAL(2,0) NULL DEFAULT NULL,
  `clients_id` INT NOT NULL,
  `pizzeria_id` INT NOT NULL,
  `hora_repartiment` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`comanda_id`, `clients_id`, `pizzeria_id`),
  INDEX `fk_comanda_clients1_idx` (`clients_id` ASC) VISIBLE,
  INDEX `fk_comanda_pizzeria1_idx` (`pizzeria_id` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_clients1`
    FOREIGN KEY (`clients_id`)
    REFERENCES `pizzeria`.`clients` (`clients_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_pizzeria1`
    FOREIGN KEY (`pizzeria_id`)
    REFERENCES `pizzeria`.`pizzeria` (`pizzeria_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`empleats` (
  `empleats_id` INT NOT NULL AUTO_INCREMENT,
  `pizzeria_id` INT NOT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `cognom1` VARCHAR(45) NULL DEFAULT NULL,
  `cognom2` VARCHAR(45) NULL DEFAULT NULL,
  `nif` VARCHAR(9) NULL DEFAULT NULL,
  `telefon` INT NULL DEFAULT NULL,
  `tipus` ENUM('cuiner/a', 'repartidor/a') NULL DEFAULT NULL COMMENT '2 valors possibles: cuiner o repartidor.',
  `comanda_id` INT NOT NULL,
  PRIMARY KEY (`empleats_id`, `pizzeria_id`, `comanda_id`),
  INDEX `fk_empleats_pizzeria1_idx` (`pizzeria_id` ASC) VISIBLE,
  INDEX `fk_empleats_comanda1_idx` (`comanda_id` ASC) VISIBLE,
  CONSTRAINT `fk_empleats_comanda1`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `pizzeria`.`comanda` (`comanda_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_empleats_pizzeria1`
    FOREIGN KEY (`pizzeria_id`)
    REFERENCES `pizzeria`.`pizzeria` (`pizzeria_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `pizzeria`.`comanda_té_productes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comanda_té_productes` (
  `comanda_id` INT NOT NULL,
  `productes_id` INT NOT NULL,
  `quantitat` INT NULL,
  PRIMARY KEY (`comanda_id`, `productes_id`),
  INDEX `fk_comanda_has_productes_productes1_idx` (`productes_id` ASC) VISIBLE,
  INDEX `fk_comanda_has_productes_comanda1_idx` (`comanda_id` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_has_productes_comanda1`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `pizzeria`.`comanda` (`comanda_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comanda_has_productes_productes1`
    FOREIGN KEY (`productes_id`)
    REFERENCES `pizzeria`.`productes` (`productes_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
