-- MySQL Script generated by MySQL Workbench
-- Mon Dec 12 09:23:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8mb3 ;
USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`clients` (
  `clients_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `telefon` INT NULL DEFAULT NULL,
  `mail` VARCHAR(45) NULL DEFAULT NULL,
  `registre` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`clients_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optica`.`client_recomana_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`client_recomana_client` (
  `client_recomana_client_id` INT NOT NULL AUTO_INCREMENT,
  `clients_clients_id` INT NOT NULL,
  `recomanacions` INT NULL DEFAULT NULL,
  PRIMARY KEY (`client_recomana_client_id`, `clients_clients_id`),
  INDEX `fk_client_recomana_client_clients1_idx` (`clients_clients_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_recomana_client_clients1`
    FOREIGN KEY (`clients_clients_id`)
    REFERENCES `optica`.`clients` (`clients_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optica`.`direccions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`direccions` (
  `direccio_id` INT NOT NULL AUTO_INCREMENT,
  `carrer` VARCHAR(45) NULL DEFAULT NULL,
  `num` INT NULL DEFAULT NULL,
  `pis` INT NULL DEFAULT NULL,
  `porta` INT NULL DEFAULT NULL,
  `ciutat` VARCHAR(45) NULL DEFAULT NULL,
  `codi_postal` INT NULL DEFAULT NULL,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  `clients_clients_id` INT NOT NULL,
  PRIMARY KEY (`direccio_id`, `clients_clients_id`),
  INDEX `fk_direccions_clients1_idx` (`clients_clients_id` ASC) VISIBLE,
  CONSTRAINT `fk_direccions_clients1`
    FOREIGN KEY (`clients_clients_id`)
    REFERENCES `optica`.`clients` (`clients_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optica`.`empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`empleats` (
  `empleats_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`empleats_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optica`.`proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`proveidor` (
  `proveidor_id` INT NOT NULL AUTO_INCREMENT,
  `proveidor_nom` VARCHAR(45) NOT NULL,
  `direccio_id` INT NOT NULL,
  PRIMARY KEY (`proveidor_id`, `direccio_id`),
  INDEX `fk_proveidor_direccio_idx` (`direccio_id` ASC) VISIBLE,
  CONSTRAINT `fk_proveidor_direccio`
    FOREIGN KEY (`direccio_id`)
    REFERENCES `optica`.`direccions` (`direccio_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optica`.`optica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`optica` (
  `optica_id` INT NOT NULL AUTO_INCREMENT,
  `empleats_empleats_id` INT NOT NULL,
  `clients_clients_id` INT NOT NULL,
  `proveidor_proveidor_id` INT NOT NULL,
  `proveidor_direccio_id` INT NOT NULL,
  PRIMARY KEY (`optica_id`, `empleats_empleats_id`, `clients_clients_id`, `proveidor_proveidor_id`, `proveidor_direccio_id`),
  INDEX `fk_optica_empleats1_idx` (`empleats_empleats_id` ASC) VISIBLE,
  INDEX `fk_optica_clients1_idx` (`clients_clients_id` ASC) VISIBLE,
  INDEX `fk_optica_proveidor1_idx` (`proveidor_proveidor_id` ASC, `proveidor_direccio_id` ASC) VISIBLE,
  CONSTRAINT `fk_optica_clients1`
    FOREIGN KEY (`clients_clients_id`)
    REFERENCES `optica`.`clients` (`clients_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_optica_empleats1`
    FOREIGN KEY (`empleats_empleats_id`)
    REFERENCES `optica`.`empleats` (`empleats_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_optica_proveidor1`
    FOREIGN KEY (`proveidor_proveidor_id` , `proveidor_direccio_id`)
    REFERENCES `optica`.`proveidor` (`proveidor_id` , `direccio_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `optica`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`ulleres` (
  `ulleres_id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `graduacio_esq` DECIMAL(2,0) NULL DEFAULT NULL,
  `graduacio_drt` DECIMAL(2,0) NULL DEFAULT NULL,
  `muntura` VARCHAR(45) NULL DEFAULT NULL,
  `color_muntura` VARCHAR(45) NULL DEFAULT NULL,
  `color_esq` VARCHAR(45) NULL DEFAULT NULL,
  `color_drt` VARCHAR(45) NULL DEFAULT NULL,
  `preu` INT NULL DEFAULT NULL,
  `proveidor_proveidor_id` INT NOT NULL,
  `proveidor_direccio_id` INT NOT NULL,
  PRIMARY KEY (`ulleres_id`),
  INDEX `fk_ulleres_proveidor1_idx` (`proveidor_proveidor_id` ASC, `proveidor_direccio_id` ASC) VISIBLE,
  CONSTRAINT `fk_ulleres_proveidor1`
    FOREIGN KEY (`proveidor_proveidor_id` , `proveidor_direccio_id`)
    REFERENCES `optica`.`proveidor` (`proveidor_id` , `direccio_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
